### PR TITLE
Update to QEMU 9.0.0, add virtio-mmio and virtio-tablet devices

### PR DESCRIPTION
**Pull request by smallsco**
- Updated to QEMU 9.0.0
 - Enabled the virtio-mmio and virtio-tablet devices
 - Fixed typo in nic mac address setting

### CODE REVIEW

**Review by FozzTexx — CHANGES_REQUESTED** [review]
Best I can tell the virtio stuff doesn't do anything. Mouse still doesn't track properly. I'd say take out the virtio/declrom lines.

**Comment by smallsco** [comment]
I'll close this for now and stick to my own fork - the virtio improvements in 9.0 doesn't fix mouse tracking 100% when running on a Linux host like it does when running on a Mac host, although it did improve the tracking significantly for me over 8.2.

**Comment by FozzTexx** [comment]
> I'll close this for now 

Ok. I'm going to go to 9.0.0 and fix that typo you found in the main branch.

> improve the tracking significantly for me over 8.2

I first tried your "increase the mouse tracking" in the control panel on 8.2 and that made it a lot more tolerable. When I tried your PR with 9.0 and virtio, it seemed to work identically to 8.2.

I was tempted to say add a conditional to check for declrom and add the lines to the Makefile to download declrom, but since it only works on a Mac host and it will *never* be a Mac host inside of the docker container I'm not sure it would be useful. Although thinking about it now, I suppose the `globaltak-start` command could probably run directly on a Mac host and doesn't have to be used only inside a container...

**Comment by smallsco** [comment]
It's confirmed to work on Mac and Windows hosts. QEMU 9.0.0 added support for virtio on Linux, but I'm guessing that the tablet driver itself isn't 100% compatible with Linux yet (I didn't try any of the other virtio devices like host file sharing which may or may not work). Hopefully in the coming weeks we'll see something that works a little better.

**Pull request closed without merging**
